services:
  web:
    build: .
    image: anguspllg/env-manager:latest
    container_name: env-manager
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - POSTGRES_HOST=db
      - ORIGIN=http://localhost:4173
      - SMTP_HOST=mailhog
    ports:
      - '4173:3000'
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: postgres
    container_name: env-manager-db
    environment:
      - POSTGRES_PORT=5432
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
