services:
  web:
    build: .
    image: anguspllg/env-manager:latest
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - POSTGRES_HOST=db
      - ORIGIN=http://localhost:4173
      - SMTP_HOST=mailhog
    ports:
      - '4173:3000'
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
      - mailhog
    networks:
      - mailhog_net

  db:
    image: postgres
    environment:
      - POSTGRES_PORT=5432
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - mailhog_net

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    networks:
      - mailhog_net
    ports:
      - '8025:8025' # Web UI
      - '1025:1025' # SMTP Server

networks:
  mailhog_net:
    driver: bridge
